"""Route-2 coupling contracts: spaces, coordinates, pairing, and adjoints."""

from .metrics import (
    ATOMIC_L1_PAIRING,
    AUTHORITATIVE_Q,
    MACE_POLAR_RADIAL_GTO_PAIRING,
    PAIRING_REGISTRY,
    PairingMetric,
    QPairing,
    get_pairing_metric,
)
from .operator import (
    AdjointValidation,
    CouplingOperator,
    validate_adjoint_dot_product,
    validate_coupling_adjoint,
)
from .point_quadrupole import (
    TRACELESS_QUADRUPOLE_BASIS,
    point_traceless_quadrupole_surface_operator,
    quadrupole_rotation_matrix,
    traceless_quadrupole_coefficients,
    traceless_quadrupole_tensors,
)
from .gaussian_quadrupole import (
    gaussian_traceless_quadrupole_potential_torch,
    gaussian_traceless_quadrupole_surface_operator,
)
from .spaces import (
    ATOMIC_L1_FIELD_DUAL_SPACE,
    ATOMIC_L1_SOURCE_SPACE,
    MACE_POLAR_RADIAL_GTO_FIELD_DUAL_SPACE,
    MACE_POLAR_RADIAL_GTO_SIGMAS_ANGSTROM,
    MACE_POLAR_RADIAL_GTO_SOURCE_SPACE,
    COORDINATE_CONTRACT_REGISTRY,
    FIELD_DUAL_SPACE_REGISTRY,
    SOURCE_SPACE_REGISTRY,
    AffineChargeCoordinates,
    AtomicL1FieldDualSpace,
    AtomicL1SourceSpace,
    ChargeConstrainedCoordinates,
    FieldDualSpace,
    LinearChargeCoordinates,
    LEGACY_UNBOUND_COORDINATE_CONTRACT,
    MACE_POLAR_RADIAL_GTO_COORDINATE_CONTRACT,
    ReducedCoordinates,
    ReducedCoordinateContract,
    SourceSpace,
    get_field_dual_space,
    get_coordinate_contract,
    get_source_space,
)

__all__ = [
    "ATOMIC_L1_FIELD_DUAL_SPACE",
    "ATOMIC_L1_PAIRING",
    "ATOMIC_L1_SOURCE_SPACE",
    "AUTHORITATIVE_Q",
    "MACE_POLAR_RADIAL_GTO_FIELD_DUAL_SPACE",
    "MACE_POLAR_RADIAL_GTO_PAIRING",
    "MACE_POLAR_RADIAL_GTO_SIGMAS_ANGSTROM",
    "MACE_POLAR_RADIAL_GTO_SOURCE_SPACE",
    "PAIRING_REGISTRY",
    "AdjointValidation",
    "AffineChargeCoordinates",
    "AtomicL1FieldDualSpace",
    "AtomicL1SourceSpace",
    "ChargeConstrainedCoordinates",
    "COORDINATE_CONTRACT_REGISTRY",
    "CouplingOperator",
    "FieldDualSpace",
    "FIELD_DUAL_SPACE_REGISTRY",
    "LinearChargeCoordinates",
    "LEGACY_UNBOUND_COORDINATE_CONTRACT",
    "MACE_POLAR_RADIAL_GTO_COORDINATE_CONTRACT",
    "PairingMetric",
    "QPairing",
    "ReducedCoordinates",
    "ReducedCoordinateContract",
    "SourceSpace",
    "SOURCE_SPACE_REGISTRY",
    "TRACELESS_QUADRUPOLE_BASIS",
    "get_field_dual_space",
    "get_coordinate_contract",
    "get_pairing_metric",
    "get_source_space",
    "gaussian_traceless_quadrupole_potential_torch",
    "gaussian_traceless_quadrupole_surface_operator",
    "point_traceless_quadrupole_surface_operator",
    "quadrupole_rotation_matrix",
    "traceless_quadrupole_coefficients",
    "traceless_quadrupole_tensors",
    "validate_adjoint_dot_product",
    "validate_coupling_adjoint",
]
