"""Scalar-first fixed-cavity continuum differentiation contracts.

A strict continuum branch must name one scalar ``G(R,c)`` first.  Its public
reaction drive, source Hessian action, mixed drive/coordinate pullback, and
fixed-source coordinate derivative are then generated by
:class:`ContinuumEnergyFunctional`; subclasses cannot supply independent
implementations of those derivatives.

The implementation is deliberately Torch-lazy so dependency-light contract
and registry tests do not acquire a Torch runtime requirement.  Merely being
callable does not admit Route-2 E/F/H/V/M capability.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np

from maple.solvation.coupling.metrics import PairingMetric
from maple.solvation.coupling.spaces import FieldDualSpace, SourceSpace


def _torch():
    return __import__("torch")


def _source_values(source_space: SourceSpace, source: object) -> np.ndarray:
    values = np.asarray(source, dtype=float)
    if values.ndim != 2 or values.shape[0] < 1:
        raise ValueError("source must be a non-empty two-dimensional array.")
    return source_space.validate(source, atom_count=values.shape[0])


def _torch_device_matches(actual: Any, configured: object) -> bool:
    """Match an allocated device to a possibly index-free Torch request.

    ``torch.tensor(..., device="cuda")`` reports an allocated device such as
    ``cuda:0`` even though ``torch.device("cuda") != torch.device("cuda:0")``.
    An omitted index deliberately means the current device, so constrain the
    index only when the configuration supplied one explicitly.
    """

    torch = _torch()
    actual_device = torch.device(actual)
    configured_device = torch.device(configured)
    return actual_device.type == configured_device.type and (
        configured_device.index is None
        or actual_device.index == configured_device.index
    )


@dataclass(frozen=True, slots=True)
class ContinuumFirstDerivativeEvaluation:
    """Energy, energy-dual drive, and fixed-source coordinate derivative."""

    energy_eV: float
    drive: np.ndarray
    coordinate_partial_eV_per_A: np.ndarray

    def __post_init__(self) -> None:
        energy = float(self.energy_eV)
        drive = np.asarray(self.drive, dtype=float)
        coordinate = np.asarray(self.coordinate_partial_eV_per_A, dtype=float)
        if (
            not np.isfinite(energy)
            or drive.ndim != 2
            or coordinate.shape != (drive.shape[0], 3)
            or not np.all(np.isfinite(drive))
            or not np.all(np.isfinite(coordinate))
        ):
            raise ValueError("continuum first-derivative evaluation is invalid.")
        drive = np.array(drive, copy=True)
        coordinate = np.array(coordinate, copy=True)
        drive.setflags(write=False)
        coordinate.setflags(write=False)
        object.__setattr__(self, "energy_eV", energy)
        object.__setattr__(self, "drive", drive)
        object.__setattr__(self, "coordinate_partial_eV_per_A", coordinate)


class ContinuumEnergyFunctional:
    """Base class whose derivatives are sealed to one Torch scalar graph."""

    __slots__ = (
        "_continuum_functional_sealed",
        "_expected_atomic_numbers",
        "_field_space",
        "_pairing",
        "_source_space",
        "_torch_device",
        "_torch_dtype",
    )

    _FINAL_DERIVATIVE_METHODS = frozenset(
        {
            "energy_torch",
            "energy_eV",
            "drive",
            "joint_position_source_hvp",
            "source_hvp",
            "source_jvp",
            "source_vjp",
            "mixed_coordinate_source_vjp",
            "coordinate_partial",
            "first_derivative_evaluation",
        }
    )

    def __init_subclass__(cls, **kwargs) -> None:
        super().__init_subclass__(**kwargs)
        forbidden = sorted(cls._FINAL_DERIVATIVE_METHODS.intersection(cls.__dict__))
        if forbidden:
            raise TypeError(
                "ContinuumEnergyFunctional derivatives are final and cannot be "
                f"overridden: {', '.join(forbidden)}."
            )
        if "_energy_torch" not in cls.__dict__:
            raise TypeError(
                "A continuum-energy subclass must implement _energy_torch only."
            )

    def __init__(
        self,
        *,
        source_space: SourceSpace,
        field_space: FieldDualSpace,
        pairing: PairingMetric,
        dtype: object,
        device: object,
        expected_atomic_numbers: tuple[int, ...] | None = None,
    ) -> None:
        if not isinstance(source_space, SourceSpace):
            raise TypeError("source_space must be SourceSpace.")
        if not isinstance(field_space, FieldDualSpace):
            raise TypeError("field_space must be FieldDualSpace.")
        if not isinstance(pairing, PairingMetric):
            raise TypeError("pairing must be PairingMetric.")
        if field_space.source_space.metadata_hash() != source_space.metadata_hash():
            raise ValueError("field_space must be dual to source_space.")
        if field_space.pairing_metric.metadata_hash() != pairing.metadata_hash():
            raise ValueError("field_space and pairing identities differ.")
        block = pairing.block
        if not np.allclose(block @ block.T, np.eye(pairing.component_count)):
            raise ValueError("continuum pairing must be an orthogonal permutation.")
        if expected_atomic_numbers is not None:
            numbers = tuple(expected_atomic_numbers)
            if not numbers or any(
                isinstance(number, bool) or not isinstance(number, int) or number < 1
                for number in numbers
            ):
                raise ValueError(
                    "expected_atomic_numbers must contain positive integers."
                )
            expected_atomic_numbers = numbers
        object.__setattr__(self, "_expected_atomic_numbers", expected_atomic_numbers)
        object.__setattr__(self, "_source_space", source_space)
        object.__setattr__(self, "_field_space", field_space)
        object.__setattr__(self, "_pairing", pairing)
        object.__setattr__(self, "_torch_dtype", dtype)
        object.__setattr__(self, "_torch_device", device)
        object.__setattr__(self, "_continuum_functional_sealed", True)

    def __setattr__(self, name: str, value: object) -> None:
        if getattr(self, "_continuum_functional_sealed", False):
            raise AttributeError(
                "ContinuumEnergyFunctional is immutable after construction."
            )
        object.__setattr__(self, name, value)

    @property
    def source_space(self) -> SourceSpace:
        return self._source_space

    @property
    def field_space(self) -> FieldDualSpace:
        return self._field_space

    @property
    def pairing(self) -> PairingMetric:
        return self._pairing

    def _energy_torch(self, positions: Any, source: Any):
        raise NotImplementedError

    def _dtype(self):
        torch = _torch()
        dtype = self._torch_dtype
        if not isinstance(dtype, torch.dtype):
            dtype = getattr(torch, str(dtype).replace("torch.", ""), None)
        if not isinstance(dtype, torch.dtype):
            raise TypeError("functional dtype is not a Torch dtype.")
        return dtype

    def _positions_tensor(
        self, geometry: object, *, atom_count: int, requires_grad: bool
    ):
        torch = _torch()
        getter = getattr(geometry, "get_positions", None)
        values = getter() if callable(getter) else geometry
        number_getter = getattr(geometry, "get_atomic_numbers", None)
        if self._expected_atomic_numbers is not None:
            if atom_count != len(self._expected_atomic_numbers):
                raise ValueError("geometry atom count does not match the functional.")
            if callable(number_getter):
                actual = tuple(int(value) for value in number_getter())
                if actual != self._expected_atomic_numbers:
                    raise ValueError(
                        "geometry atomic numbers do not match the functional."
                    )
        positions = np.asarray(values, dtype=float)
        if positions.shape != (atom_count, 3) or not np.all(np.isfinite(positions)):
            raise ValueError(
                f"geometry positions must be finite with shape ({atom_count}, 3)."
            )
        return torch.tensor(
            positions,
            dtype=self._dtype(),
            device=self._torch_device,
            requires_grad=requires_grad,
        )

    def _source_tensor(self, source: object, *, requires_grad: bool):
        torch = _torch()
        values = np.asarray(source, dtype=float)
        if (
            values.ndim != 2
            or values.shape[0] < 1
            or values.shape[1] != self.source_space.component_count
            or not np.all(np.isfinite(values))
        ):
            raise ValueError(
                "source must be finite with shape "
                f"(atom_count, {self.source_space.component_count})."
            )
        return torch.tensor(
            values,
            dtype=self._dtype(),
            device=self._torch_device,
            requires_grad=requires_grad,
        )

    def energy_torch(self, positions: Any, source: Any):
        torch = _torch()
        if not torch.is_tensor(positions) or not torch.is_tensor(source):
            raise TypeError("positions and source must be Torch tensors.")
        if (
            positions.ndim != 2
            or positions.shape[1] != 3
            or source.ndim != 2
            or source.shape[0] != positions.shape[0]
            or source.shape[1] != self.source_space.component_count
            or not torch.is_floating_point(positions)
            or not torch.is_floating_point(source)
            or positions.dtype != source.dtype
            or positions.device != source.device
            or positions.dtype != self._dtype()
            or not _torch_device_matches(positions.device, self._torch_device)
            or not bool(torch.isfinite(positions).all())
            or not bool(torch.isfinite(source).all())
        ):
            raise ValueError(
                "positions/source do not satisfy the continuum scalar contract."
            )
        energy = self._energy_torch(positions, source)
        if not torch.is_tensor(energy) or energy.numel() != 1:
            raise TypeError("_energy_torch must return one scalar Torch tensor.")
        energy = energy.reshape(())
        if not bool(torch.isfinite(energy)):
            raise ValueError("continuum energy is non-finite.")
        return energy

    def energy_eV(self, geometry: object, source: object) -> float:
        values = _source_values(self.source_space, source)
        positions = self._positions_tensor(
            geometry, atom_count=values.shape[0], requires_grad=False
        )
        source_tensor = self._source_tensor(values, requires_grad=False)
        result = float(self.energy_torch(positions, source_tensor).detach().cpu())
        if not np.isfinite(result):
            raise RuntimeError("continuum energy is non-finite.")
        return result

    def _drive_graph(
        self,
        geometry: object,
        source: object,
        *,
        coordinate_grad: bool,
        create_graph: bool,
    ):
        torch = _torch()
        values = _source_values(self.source_space, source)
        positions = self._positions_tensor(
            geometry, atom_count=values.shape[0], requires_grad=coordinate_grad
        )
        source_tensor = self._source_tensor(values, requires_grad=True)
        energy = self.energy_torch(positions, source_tensor)
        if energy.requires_grad:
            (source_covector,) = torch.autograd.grad(
                energy,
                (source_tensor,),
                create_graph=create_graph,
                retain_graph=coordinate_grad,
                allow_unused=True,
            )
        else:
            source_covector = None
        if source_covector is None:
            source_covector = torch.zeros_like(source_tensor)
        indices = torch.as_tensor(
            np.argsort(self.pairing.field_to_source_indices),
            dtype=torch.long,
            device=source_tensor.device,
        )
        drive = torch.index_select(source_covector, -1, indices)
        return positions, source_tensor, energy, drive

    def drive(self, geometry: object, source: object) -> np.ndarray:
        _, _, _, drive = self._drive_graph(
            geometry,
            source,
            coordinate_grad=False,
            create_graph=False,
        )
        values = np.asarray(drive.detach().cpu(), dtype=float).copy()
        return self.field_space.validate(
            values, atom_count=values.shape[0], name="continuum drive"
        )

    def first_derivative_evaluation(
        self, geometry: object, source: object
    ) -> ContinuumFirstDerivativeEvaluation:
        """Evaluate all first derivatives from one sealed scalar graph."""

        torch = _torch()
        values = _source_values(self.source_space, source)
        positions = self._positions_tensor(
            geometry, atom_count=values.shape[0], requires_grad=True
        )
        source_tensor = self._source_tensor(values, requires_grad=True)
        energy = self.energy_torch(positions, source_tensor)
        if energy.requires_grad:
            coordinate, source_covector = torch.autograd.grad(
                energy,
                (positions, source_tensor),
                create_graph=False,
                allow_unused=True,
            )
        else:
            coordinate = source_covector = None
        if coordinate is None:
            coordinate = torch.zeros_like(positions)
        if source_covector is None:
            source_covector = torch.zeros_like(source_tensor)
        inverse = torch.as_tensor(
            np.argsort(self.pairing.field_to_source_indices),
            dtype=torch.long,
            device=source_tensor.device,
        )
        drive = torch.index_select(source_covector, -1, inverse)
        drive_values = self.field_space.validate(
            np.asarray(drive.detach().cpu(), dtype=float),
            atom_count=values.shape[0],
            name="continuum drive",
        )
        coordinate_values = np.asarray(coordinate.detach().cpu(), dtype=float)
        return ContinuumFirstDerivativeEvaluation(
            energy_eV=float(energy.detach().cpu()),
            drive=drive_values,
            coordinate_partial_eV_per_A=coordinate_values,
        )

    def source_hvp(
        self, geometry: object, source: object, source_direction: object
    ) -> np.ndarray:
        torch = _torch()
        values = _source_values(self.source_space, source)
        direction = self.source_space.validate(
            source_direction,
            atom_count=values.shape[0],
            name="source_direction",
        )
        positions = self._positions_tensor(
            geometry, atom_count=values.shape[0], requires_grad=False
        )
        source_tensor = self._source_tensor(values, requires_grad=False)
        direction_tensor = torch.as_tensor(
            direction, dtype=source_tensor.dtype, device=source_tensor.device
        )

        def scalar(candidate):
            return self.energy_torch(positions, candidate)

        _, hvp = torch.autograd.functional.hvp(
            scalar,
            source_tensor,
            direction_tensor,
            create_graph=False,
            strict=False,
        )
        result = np.asarray(hvp.detach().cpu(), dtype=float).copy()
        return self.source_space.validate(
            result, atom_count=values.shape[0], name="continuum source HVP"
        )

    def joint_position_source_hvp(
        self,
        geometry: object,
        source: object,
        position_direction: object,
        source_direction: object,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Apply the joint Hessian of the sealed scalar ``G(R,c)``.

        The returned pair is

        ``(G_RR h + G_Rc dc, G_cR h + G_cc dc)``.

        Both blocks are generated in one Torch HVP from the exact scalar graph;
        subclasses cannot supply a separately coded force-response formula.
        """

        torch = _torch()
        values = _source_values(self.source_space, source)
        count = values.shape[0]
        coordinate_direction = np.asarray(position_direction, dtype=float)
        if coordinate_direction.shape != (count, 3) or not np.all(
            np.isfinite(coordinate_direction)
        ):
            raise ValueError(
                "position_direction must be finite with shape " f"{(count, 3)}."
            )
        source_direction_values = self.source_space.validate(
            source_direction,
            atom_count=count,
            name="source_direction",
        )
        positions = self._positions_tensor(
            geometry, atom_count=count, requires_grad=False
        )
        source_tensor = self._source_tensor(values, requires_grad=False)
        position_direction_tensor = torch.as_tensor(
            np.array(coordinate_direction, copy=True),
            dtype=positions.dtype,
            device=positions.device,
        )
        source_direction_tensor = torch.as_tensor(
            np.array(source_direction_values, copy=True),
            dtype=source_tensor.dtype,
            device=source_tensor.device,
        )

        _, (position_hvp, source_hvp) = torch.autograd.functional.hvp(
            lambda candidate_positions, candidate_source: self.energy_torch(
                candidate_positions, candidate_source
            ),
            (positions, source_tensor),
            (position_direction_tensor, source_direction_tensor),
            create_graph=False,
            strict=False,
        )
        position_result = np.asarray(position_hvp.detach().cpu(), dtype=float).copy()
        if position_result.shape != (count, 3) or not np.all(
            np.isfinite(position_result)
        ):
            raise RuntimeError(
                "continuum joint position HVP must be finite with shape (N,3)."
            )
        source_result = np.asarray(source_hvp.detach().cpu(), dtype=float).copy()
        source_result = self.source_space.validate(
            source_result,
            atom_count=count,
            name="continuum joint source HVP",
        )
        return position_result, source_result

    def source_jvp(
        self, geometry: object, source: object, source_direction: object
    ) -> np.ndarray:
        source_covector = self.source_hvp(geometry, source, source_direction)
        return self.field_space.validate(
            self.pairing.source_to_field_dual(source_covector),
            atom_count=source_covector.shape[0],
            name="continuum drive JVP",
        )

    def source_vjp(
        self, geometry: object, source: object, field_cotangent: object
    ) -> np.ndarray:
        torch = _torch()
        values = _source_values(self.source_space, source)
        cotangent = self.field_space.validate(
            field_cotangent,
            atom_count=values.shape[0],
            name="field_cotangent",
        )
        positions = self._positions_tensor(
            geometry, atom_count=values.shape[0], requires_grad=False
        )
        source_tensor = self._source_tensor(values, requires_grad=False)
        cotangent_tensor = torch.as_tensor(
            cotangent, dtype=source_tensor.dtype, device=source_tensor.device
        )

        def drive_graph(candidate):
            candidate = candidate.requires_grad_(True)
            energy = self.energy_torch(positions, candidate)
            if energy.requires_grad:
                (source_covector,) = torch.autograd.grad(
                    energy,
                    (candidate,),
                    create_graph=True,
                    allow_unused=True,
                )
            else:
                source_covector = None
            if source_covector is None:
                source_covector = torch.zeros_like(candidate)
            inverse = torch.as_tensor(
                np.argsort(self.pairing.field_to_source_indices),
                dtype=torch.long,
                device=candidate.device,
            )
            return torch.index_select(source_covector, -1, inverse)

        _, vjp = torch.autograd.functional.vjp(
            drive_graph,
            source_tensor,
            v=cotangent_tensor,
            create_graph=False,
            strict=False,
        )
        result = np.asarray(vjp.detach().cpu(), dtype=float).copy()
        return self.source_space.validate(
            result, atom_count=values.shape[0], name="continuum drive VJP"
        )

    def mixed_coordinate_source_vjp(
        self, geometry: object, source: object, field_cotangent: object
    ) -> np.ndarray:
        """Apply ``(partial_R drive(R,c)).T`` at fixed source.

        The drive is differentiated from the same sealed scalar graph.  This
        method exists for state-equation coordinate pullbacks; it is not a
        second continuum-force implementation and does not admit a capability.
        """

        torch = _torch()
        values = _source_values(self.source_space, source)
        cotangent = self.field_space.validate(
            field_cotangent,
            atom_count=values.shape[0],
            name="field_cotangent",
        )
        positions, _, _, drive = self._drive_graph(
            geometry,
            values,
            coordinate_grad=True,
            create_graph=True,
        )
        cotangent_tensor = torch.as_tensor(
            cotangent, dtype=drive.dtype, device=drive.device
        )
        contraction = torch.sum(drive * cotangent_tensor)
        if contraction.requires_grad:
            (gradient,) = torch.autograd.grad(
                contraction,
                (positions,),
                create_graph=False,
                allow_unused=True,
            )
        else:
            gradient = None
        if gradient is None:
            gradient = torch.zeros_like(positions)
        result = np.asarray(gradient.detach().cpu(), dtype=float).copy()
        if result.shape != tuple(positions.shape) or not np.all(np.isfinite(result)):
            raise RuntimeError("continuum mixed coordinate/source VJP is invalid.")
        return result

    def coordinate_partial(self, geometry: object, source: object) -> np.ndarray:
        torch = _torch()
        values = _source_values(self.source_space, source)
        positions = self._positions_tensor(
            geometry, atom_count=values.shape[0], requires_grad=True
        )
        source_tensor = self._source_tensor(values, requires_grad=False)
        energy = self.energy_torch(positions, source_tensor)
        if energy.requires_grad:
            (gradient,) = torch.autograd.grad(
                energy,
                (positions,),
                create_graph=False,
                allow_unused=True,
            )
        else:
            gradient = None
        if gradient is None:
            gradient = torch.zeros_like(positions)
        result = np.asarray(gradient.detach().cpu(), dtype=float).copy()
        if result.shape != tuple(positions.shape) or not np.all(np.isfinite(result)):
            raise RuntimeError("continuum coordinate partial is invalid.")
        return result


__all__ = ["ContinuumEnergyFunctional", "ContinuumFirstDerivativeEvaluation"]
