"""Sealed same-scalar smooth harmonic Galerkin continuum candidate.

The complete ``R -> E,K,V -> A,S -> G`` path is assembled in Torch by
``harmonic_torch_primitives``. All continuum derivatives are generated by
:class:`ContinuumEnergyFunctional`; this disabled research candidate cannot
provide independent drive or force formulas.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import numpy as np

from maple.solvation.api.capabilities import CapabilityStatus
from maple.solvation.api.profiles import (
    MACE_POLAR_RADIAL_GTO_COUPLING_ID,
    SMOOTH_HARMONIC_CAVITY_PROFILE_ID,
    SMOOTH_HARMONIC_GALERKIN_CPCM_CONTINUUM_PROFILE_ID,
    SMOOTH_HARMONIC_GALERKIN_CONFIGURATION_CONTRACT_ID,
)
from maple.solvation.api.scalar_registry import (
    OPERATIONAL_MACEPOLAR_ANALYTIC_GAUSSIAN_MULTIPOLE_SMOOTH_HARMONIC_GALERKIN_CPCM_V1,
    VARIATIONAL_MACEPOLAR_ANALYTIC_GAUSSIAN_MULTIPOLE_ENERGYGRADIENT_SMOOTH_HARMONIC_GALERKIN_CPCM_V1,
    VARIATIONAL_MACEPOLAR_ENERGYGRADIENT_SMOOTH_HARMONIC_GALERKIN_CPCM_V1,
)
from maple.solvation.coupling.metrics import MACE_POLAR_RADIAL_GTO_PAIRING
from maple.solvation.coupling.spaces import (
    MACE_POLAR_RADIAL_GTO_FIELD_DUAL_SPACE,
    MACE_POLAR_RADIAL_GTO_SOURCE_SPACE,
)

from .functional import ContinuumEnergyFunctional
from .harmonic_coefficients import _bounded_lmax, _positive_int
from .harmonic_torch_primitives import (
    _assemble_gaussian_source,
    _assemble_single_layer,
    _assemble_weighted_basis,
    _torch,
)

SMOOTH_HARMONIC_GALERKIN_TORCH_FUNCTIONAL_PROVIDER_ID = (
    "maple.route2.continuum.smooth-harmonic-galerkin-torch-functional.impl.v1"
)
SMOOTH_HARMONIC_GALERKIN_TORCH_FUNCTIONAL_CONTRACT_ID = (
    "maple.route2.continuum.smooth-harmonic-galerkin-same-scalar.v1"
)
_MINIMUM_RELATIVE_BASIS_SINGULAR_VALUE = 1.0e-10
_MAXIMUM_REFERENCE_CONDITION_NUMBER = 1.0e12


def _sha(payload: object) -> str:
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()


def _implementation_sha256() -> tuple[tuple[str, str], ...]:
    continuum = Path(__file__).resolve().parent
    files = {
        "functional.py": continuum / "functional.py",
        "harmonic_coefficients.py": continuum / "harmonic_coefficients.py",
        "harmonic_exposure.py": continuum / "harmonic_exposure.py",
        "harmonic_gaussian_source.py": continuum / "harmonic_gaussian_source.py",
        "harmonic_single_layer.py": continuum / "harmonic_single_layer.py",
        "harmonic_torch_functional.py": Path(__file__),
        "harmonic_torch_primitives.py": continuum / "harmonic_torch_primitives.py",
        "harmonic_weighted_galerkin.py": continuum / "harmonic_weighted_galerkin.py",
    }
    return tuple(
        (name, hashlib.sha256(path.read_bytes()).hexdigest())
        for name, path in sorted(files.items())
    )


def _positive_float(value: object, *, name: str) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float, np.number)):
        raise TypeError(f"{name} must be a real scalar.")
    result = float(value)
    if not np.isfinite(result) or result <= 0.0:
        raise ValueError(f"{name} must be finite and positive.")
    return result


def _bounded_order(value: object, *, name: str) -> int:
    result = _positive_int(value, name=name)
    if result > 4096:
        raise ValueError(f"{name} exceeds the bounded contract.")
    return result


def _coefficient_topology_payload(
    *,
    atomic_numbers: tuple[int, ...],
    radii_angstrom: tuple[float, ...],
    surface_lmax: int,
    exposure_lmax: int,
) -> dict[str, object]:
    """Return the geometry-independent coefficient ownership contract."""

    physical_lmax = surface_lmax + exposure_lmax
    return {
        "contract": "smooth-harmonic-fixed-coefficient-topology-v1",
        "provider_id": SMOOTH_HARMONIC_GALERKIN_TORCH_FUNCTIONAL_PROVIDER_ID,
        "atomic_numbers": atomic_numbers,
        "radii_angstrom": radii_angstrom,
        "atom_order": "input-order",
        "coefficient_order": "atom-major/l-ascending/m-ascending/real-harmonic",
        "surface_lmax": surface_lmax,
        "surface_coefficients_per_atom": (surface_lmax + 1) ** 2,
        "exposure_lmax": exposure_lmax,
        "physical_lmax": physical_lmax,
        "physical_coefficients_per_atom": (physical_lmax + 1) ** 2,
        "active_coefficient_deletion": False,
    }


class SmoothWeightedHarmonicGalerkinFunctionalCandidate(ContinuumEnergyFunctional):
    """Moving smooth harmonic cavity assembled inside one sealed scalar."""

    __slots__ = (
        "_candidate_configuration_sha256",
        "_candidate_provenance_sha256",
        "_candidate_topology_sha256",
        "_exposure_lmax",
        "_exposure_radial_order",
        "_green_radial_order",
        "_radii_angstrom",
        "_runtime_device",
        "_runtime_dtype",
        "_scalar_id",
        "_source_radial_order",
        "_surface_lmax",
        "_transition_width_angstrom2",
    )

    provider_id = SMOOTH_HARMONIC_GALERKIN_TORCH_FUNCTIONAL_PROVIDER_ID
    functional_contract_id = SMOOTH_HARMONIC_GALERKIN_TORCH_FUNCTIONAL_CONTRACT_ID
    continuum_profile_id = SMOOTH_HARMONIC_GALERKIN_CPCM_CONTINUUM_PROFILE_ID
    cavity_profile_id = SMOOTH_HARMONIC_CAVITY_PROFILE_ID
    coupling_id = MACE_POLAR_RADIAL_GTO_COUPLING_ID
    configuration_contract_id = SMOOTH_HARMONIC_GALERKIN_CONFIGURATION_CONTRACT_ID
    capabilities = CapabilityStatus()
    scalar_first = True
    reciprocal = True
    linear_response = True
    fixed_topology = True
    fixed_cavity_descriptor = False
    source_dependent_geometry = False
    electrostatics_only = True
    include_nonpolar = False
    coefficient_action_is_so3_representation = True
    full_geometry_intertwiner_assembly_available = True
    moving_cavity_coordinate_derivative_available = True
    derivatives_generated_from_same_scalar = True
    laboratory_fixed_surface_grid = False
    registered_scalar = True
    tier_v_rotation_admitted = False
    tier_v_admitted = False

    def __init__(
        self,
        *,
        atomic_numbers: tuple[int, ...],
        radii_angstrom: tuple[float, ...],
        transition_width_angstrom2: float,
        surface_lmax: int,
        exposure_lmax: int,
        exposure_radial_quadrature_order: int = 96,
        source_radial_quadrature_order: int = 128,
        green_radial_quadrature_order: int = 128,
        dtype: object,
        device: object,
        scalar_id: str = (
            VARIATIONAL_MACEPOLAR_ENERGYGRADIENT_SMOOTH_HARMONIC_GALERKIN_CPCM_V1
        ),
    ) -> None:
        numbers = tuple(atomic_numbers)
        if not numbers or any(
            isinstance(number, bool) or not isinstance(number, int) or number < 1
            for number in numbers
        ):
            raise ValueError("atomic_numbers must contain positive integers.")
        radii = tuple(
            _positive_float(value, name=f"radii_angstrom[{index}]")
            for index, value in enumerate(radii_angstrom)
        )
        if len(radii) != len(numbers):
            raise ValueError("radii_angstrom must have one value per atom.")
        surface_maximum = _bounded_lmax(surface_lmax)
        exposure_maximum = _bounded_lmax(exposure_lmax)
        if exposure_maximum < 2 * surface_maximum:
            raise ValueError("exposure_lmax must be at least twice surface_lmax.")
        physical_lmax = surface_maximum + exposure_maximum
        _bounded_lmax(physical_lmax)
        exposure_order = _bounded_order(
            exposure_radial_quadrature_order,
            name="exposure_radial_quadrature_order",
        )
        source_order = _bounded_order(
            source_radial_quadrature_order,
            name="source_radial_quadrature_order",
        )
        green_order = _bounded_order(
            green_radial_quadrature_order,
            name="green_radial_quadrature_order",
        )
        width = _positive_float(
            transition_width_angstrom2, name="transition_width_angstrom2"
        )
        normalized_scalar_id = str(scalar_id).strip()
        if normalized_scalar_id not in {
            OPERATIONAL_MACEPOLAR_ANALYTIC_GAUSSIAN_MULTIPOLE_SMOOTH_HARMONIC_GALERKIN_CPCM_V1,
            VARIATIONAL_MACEPOLAR_ENERGYGRADIENT_SMOOTH_HARMONIC_GALERKIN_CPCM_V1,
            VARIATIONAL_MACEPOLAR_ANALYTIC_GAUSSIAN_MULTIPOLE_ENERGYGRADIENT_SMOOTH_HARMONIC_GALERKIN_CPCM_V1,
        }:
            raise ValueError(
                "The harmonic continuum scalar binding is not preregistered."
            )
        runtime_dtype = str(dtype)
        runtime_device = str(device)
        topology = _sha(
            _coefficient_topology_payload(
                atomic_numbers=numbers,
                radii_angstrom=radii,
                surface_lmax=surface_maximum,
                exposure_lmax=exposure_maximum,
            )
        )
        configuration_payload = {
            "provider_id": self.provider_id,
            "scalar_id": normalized_scalar_id,
            "functional_contract_id": self.functional_contract_id,
            "continuum_profile_id": self.continuum_profile_id,
            "cavity_profile_id": self.cavity_profile_id,
            "coupling_id": self.coupling_id,
            "configuration_contract_id": self.configuration_contract_id,
            "atomic_numbers": numbers,
            "radii_angstrom": radii,
            "transition_width_angstrom2": width,
            "surface_lmax": surface_maximum,
            "exposure_lmax": exposure_maximum,
            "physical_lmax": physical_lmax,
            "exposure_radial_quadrature_order": exposure_order,
            "source_radial_quadrature_order": source_order,
            "green_radial_quadrature_order": green_order,
            "coefficient_topology_sha256": topology,
            "source_space_sha256": MACE_POLAR_RADIAL_GTO_SOURCE_SPACE.metadata_hash(),
            "field_space_sha256": MACE_POLAR_RADIAL_GTO_FIELD_DUAL_SPACE.metadata_hash(),
            "pairing_sha256": MACE_POLAR_RADIAL_GTO_PAIRING.metadata_hash(),
            "runtime_dtype": runtime_dtype,
            "runtime_device": runtime_device,
            "assembly": "A=E.T K E; S=E.T V; G=-1/2 (Sc).T A^-1 (Sc)",
            "angular_quadrature": "finite-band-exact-contractions-only",
            "geometry_quadrature": "invariant-one-dimensional",
            "derivative_route": "sealed-same-scalar-autograd",
            "implementation_sha256": _implementation_sha256(),
            "capabilities": "none",
        }
        configuration = _sha(configuration_payload)
        provenance = _sha(
            {
                "provider_id": self.provider_id,
                "configuration_sha256": configuration,
                "implementation_sha256": _implementation_sha256(),
                "tier_v_admission": "disabled",
            }
        )
        object.__setattr__(self, "_radii_angstrom", radii)
        object.__setattr__(self, "_transition_width_angstrom2", width)
        object.__setattr__(self, "_surface_lmax", surface_maximum)
        object.__setattr__(self, "_exposure_lmax", exposure_maximum)
        object.__setattr__(self, "_exposure_radial_order", exposure_order)
        object.__setattr__(self, "_source_radial_order", source_order)
        object.__setattr__(self, "_green_radial_order", green_order)
        object.__setattr__(self, "_runtime_dtype", runtime_dtype)
        object.__setattr__(self, "_runtime_device", runtime_device)
        object.__setattr__(self, "_scalar_id", normalized_scalar_id)
        object.__setattr__(self, "_candidate_topology_sha256", topology)
        object.__setattr__(self, "_candidate_configuration_sha256", configuration)
        object.__setattr__(self, "_candidate_provenance_sha256", provenance)
        super().__init__(
            source_space=MACE_POLAR_RADIAL_GTO_SOURCE_SPACE,
            field_space=MACE_POLAR_RADIAL_GTO_FIELD_DUAL_SPACE,
            pairing=MACE_POLAR_RADIAL_GTO_PAIRING,
            dtype=dtype,
            device=device,
            expected_atomic_numbers=numbers,
        )

    @property
    def scalar_id(self) -> str:
        return self._scalar_id

    @property
    def radii_angstrom(self) -> tuple[float, ...]:
        return self._radii_angstrom

    @property
    def surface_lmax(self) -> int:
        return self._surface_lmax

    @property
    def exposure_lmax(self) -> int:
        return self._exposure_lmax

    @property
    def physical_lmax(self) -> int:
        return self._surface_lmax + self._exposure_lmax

    @property
    def provenance_sha256(self) -> str:
        self.configuration_sha256()
        return self._candidate_provenance_sha256

    def configuration_sha256(self) -> str:
        topology = self.topology_sha256()
        current = _sha(
            {
                "provider_id": self.provider_id,
                "scalar_id": self.scalar_id,
                "functional_contract_id": self.functional_contract_id,
                "continuum_profile_id": self.continuum_profile_id,
                "cavity_profile_id": self.cavity_profile_id,
                "coupling_id": self.coupling_id,
                "configuration_contract_id": self.configuration_contract_id,
                "atomic_numbers": self._expected_atomic_numbers,
                "radii_angstrom": self._radii_angstrom,
                "transition_width_angstrom2": self._transition_width_angstrom2,
                "surface_lmax": self._surface_lmax,
                "exposure_lmax": self._exposure_lmax,
                "physical_lmax": self.physical_lmax,
                "exposure_radial_quadrature_order": self._exposure_radial_order,
                "source_radial_quadrature_order": self._source_radial_order,
                "green_radial_quadrature_order": self._green_radial_order,
                "coefficient_topology_sha256": topology,
                "source_space_sha256": MACE_POLAR_RADIAL_GTO_SOURCE_SPACE.metadata_hash(),
                "field_space_sha256": MACE_POLAR_RADIAL_GTO_FIELD_DUAL_SPACE.metadata_hash(),
                "pairing_sha256": MACE_POLAR_RADIAL_GTO_PAIRING.metadata_hash(),
                "runtime_dtype": self._runtime_dtype,
                "runtime_device": self._runtime_device,
                "assembly": "A=E.T K E; S=E.T V; G=-1/2 (Sc).T A^-1 (Sc)",
                "angular_quadrature": "finite-band-exact-contractions-only",
                "geometry_quadrature": "invariant-one-dimensional",
                "derivative_route": "sealed-same-scalar-autograd",
                "implementation_sha256": _implementation_sha256(),
                "capabilities": "none",
            }
        )
        if current != self._candidate_configuration_sha256:
            raise RuntimeError("smooth harmonic functional configuration drifted.")
        expected_provenance = _sha(
            {
                "provider_id": self.provider_id,
                "configuration_sha256": current,
                "implementation_sha256": _implementation_sha256(),
                "tier_v_admission": "disabled",
            }
        )
        if expected_provenance != self._candidate_provenance_sha256:
            raise RuntimeError("smooth harmonic functional provenance drifted.")
        return current

    def topology_sha256(self) -> str:
        """Return the fixed coefficient dimension/owner/order identity."""

        current = _sha(
            _coefficient_topology_payload(
                atomic_numbers=self._expected_atomic_numbers,
                radii_angstrom=self._radii_angstrom,
                surface_lmax=self._surface_lmax,
                exposure_lmax=self._exposure_lmax,
            )
        )
        if current != self._candidate_topology_sha256:
            raise RuntimeError("smooth harmonic coefficient topology drifted.")
        return current

    def _assemble_torch(self, positions: Any):
        weighted_basis = _assemble_weighted_basis(
            positions,
            radii=self._radii_angstrom,
            transition_width=self._transition_width_angstrom2,
            surface_lmax=self._surface_lmax,
            exposure_lmax=self._exposure_lmax,
            radial_order=self._exposure_radial_order,
        )
        raw_single_layer = _assemble_single_layer(
            positions,
            radii=self._radii_angstrom,
            lmax=self.physical_lmax,
            radial_order=self._green_radial_order,
        )
        raw_source = _assemble_gaussian_source(
            positions,
            radii=self._radii_angstrom,
            lmax=self.physical_lmax,
            radial_order=self._source_radial_order,
        )
        surface = weighted_basis.T @ raw_single_layer @ weighted_basis
        surface = 0.5 * (surface + surface.T)
        source_operator = weighted_basis.T @ raw_source

        singular_values = _torch().linalg.svdvals(weighted_basis).detach()
        relative_basis = float((singular_values[-1] / singular_values[0]).cpu())
        eigenvalues = _torch().linalg.eigvalsh(surface).detach()
        minimum = float(eigenvalues[0].cpu())
        condition = float((eigenvalues[-1] / eigenvalues[0]).cpu())
        if (
            not np.isfinite(relative_basis)
            or relative_basis <= _MINIMUM_RELATIVE_BASIS_SINGULAR_VALUE
            or not np.isfinite(minimum)
            or minimum <= 1.0e-12
            or not np.isfinite(condition)
            or condition > _MAXIMUM_REFERENCE_CONDITION_NUMBER
        ):
            raise ValueError(
                "smooth harmonic stationary assembly failed its rank/SPD gate."
            )
        return weighted_basis, raw_single_layer, raw_source, surface, source_operator

    def _energy_torch(self, positions: Any, source: Any):
        self.configuration_sha256()
        _, _, _, surface, source_operator = self._assemble_torch(positions)
        right_hand_side = source_operator @ source.reshape(-1)
        surface_state = _torch().linalg.solve(surface, right_hand_side)
        return -0.5 * (right_hand_side @ surface_state)

    def debug_geometry_matrices(self, geometry: object) -> dict[str, np.ndarray]:
        """Return detached matrices for parity tests; never an admission API."""

        positions = self._positions_tensor(
            geometry,
            atom_count=len(self._radii_angstrom),
            requires_grad=False,
        )
        names = (
            "weighted_basis",
            "raw_single_layer",
            "raw_source",
            "surface_operator",
            "source_operator",
        )
        matrices = self._assemble_torch(positions)
        return {
            name: np.asarray(matrix.detach().cpu(), dtype=float).copy()
            for name, matrix in zip(names, matrices)
        }

    def runtime_provenance(self) -> tuple[tuple[str, object], ...]:
        return tuple(
            sorted(
                {
                    "provider_id": self.provider_id,
                    "provenance_sha256": self.provenance_sha256,
                    "configuration_sha256": self.configuration_sha256(),
                    "coefficient_topology_sha256": self.topology_sha256(),
                    "stationary_scalar": "-1/2 (S c)^T A^-1 (S c)",
                    "geometry_assembly": "same-scalar-E-K-V",
                    "angular_quadrature": "finite-band-exact-contractions-only",
                    "laboratory_fixed_surface_grid": False,
                    "registered_scalar": True,
                    "tier_v_admission": "disabled",
                    "capabilities": "none",
                }.items()
            )
        )


__all__ = [
    "SMOOTH_HARMONIC_GALERKIN_TORCH_FUNCTIONAL_CONTRACT_ID",
    "SMOOTH_HARMONIC_GALERKIN_TORCH_FUNCTIONAL_PROVIDER_ID",
    "SmoothWeightedHarmonicGalerkinFunctionalCandidate",
]
