"""Disabled finite-dielectric smooth-partition harmonic ddPCM scalar.

The implementation retains the fixed local-potential Schwarz topology of the
validated harmonic ddCOSMO candidate, but replaces uniform COSMO dielectric
scaling by the published finite-dielectric two-stage equation

``A_epsilon G = A_infinity F`` and ``L X = G`` with ``F=-B c``.

The double-layer stage uses ddX's centered smooth characteristic and exterior
multipole continuation, assembled without a laboratory angular grid.  The
physical on-shell scalar is ``0.5*c.T*C*X``.  The first-stage and Schwarz
operators are generally nonsymmetric, so all derivatives are generated by
autodifferentiating this scalar through both solves.  This is a research
candidate and exposes no public E/F/H/V/M capability.
"""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Any

import numpy as np

from maple.solvation.api.capabilities import CapabilityStatus
from maple.solvation.coupling.metrics import ATOMIC_L1_PAIRING
from maple.solvation.coupling.spaces import (
    ATOMIC_L1_FIELD_DUAL_SPACE,
    ATOMIC_L1_SOURCE_SPACE,
)

from .harmonic_ddcosmo_functional import (
    _MAXIMUM_CONDITION_NUMBER,
    _MINIMUM_RELATIVE_SINGULAR_VALUE,
    _bounded_order,
    _sha,
    SmoothPartitionHarmonicDDCOSMOFunctionalCandidate,
)
from .harmonic_ddpcm_primitives import _assemble_point_ddpcm

SMOOTH_PARTITION_HARMONIC_DDPCM_PROVIDER_ID = (
    "maple.route2.continuum.smooth-partition-harmonic-ddpcm.impl.v1"
)
SMOOTH_PARTITION_HARMONIC_DDPCM_CONTRACT_ID = (
    "maple.route2.continuum.fixed-local-potential-two-stage-ddpcm-scalar.v1"
)
SMOOTH_PARTITION_HARMONIC_DDPCM_PROFILE_ID = (
    "smooth-partition-harmonic-ddpcm-point-l1-v1"
)
SMOOTH_PARTITION_HARMONIC_DDPCM_SCALAR_ID = (
    "route2-research-macepolar-frozen-point-l1-smoothharmonic-ddpcm-v1"
)
DDX_EQUATION_REFERENCE_COMMIT = "4d79e3d9caeae5e602683572a71cb550414f9b09"


def _implementation_sha256() -> tuple[tuple[str, str], ...]:
    directory = Path(__file__).resolve().parent
    names = (
        "functional.py",
        "harmonic_coefficients.py",
        "harmonic_ddcosmo_functional.py",
        "harmonic_ddpcm_functional.py",
        "harmonic_ddpcm_primitives.py",
        "harmonic_exposure.py",
        "harmonic_point_source.py",
        "harmonic_schwarz_primitives.py",
        "harmonic_torch_primitives.py",
    )
    return tuple(
        (name, hashlib.sha256((directory / name).read_bytes()).hexdigest())
        for name in names
    )


class SmoothPartitionHarmonicDDPCMFunctionalCandidate(
    SmoothPartitionHarmonicDDCOSMOFunctionalCandidate
):
    """Fixed-coefficient, scalar-first, point-l<=1 harmonic ddPCM."""

    __slots__ = ("_double_layer_radial_order",)

    provider_id = SMOOTH_PARTITION_HARMONIC_DDPCM_PROVIDER_ID
    functional_contract_id = SMOOTH_PARTITION_HARMONIC_DDPCM_CONTRACT_ID
    continuum_profile_id = SMOOTH_PARTITION_HARMONIC_DDPCM_PROFILE_ID
    scalar_id = SMOOTH_PARTITION_HARMONIC_DDPCM_SCALAR_ID
    capabilities = CapabilityStatus()
    scalar_first = True
    linear_response = True
    reciprocal_energy_hessian = True
    conventional_receiver_equals_energy_gradient = False
    fixed_topology = True
    source_dependent_geometry = False
    electrostatics_only = True
    include_nonpolar = False
    coefficient_action_is_so3_representation = True
    laboratory_fixed_surface_grid = False
    smooth_partition = True
    derivatives_generated_from_same_scalar = True
    finite_dielectric_parameterization = True
    uniform_cosmo_dielectric_scaling = False
    tier_v_admitted = False
    point_monopoles_only = False

    def __init__(
        self,
        *,
        atomic_numbers: tuple[int, ...],
        radii_angstrom: tuple[float, ...],
        transition_width_angstrom2: float,
        surface_lmax: int,
        partition_lmax: int,
        partition_radial_quadrature_order: int = 96,
        source_radial_quadrature_order: int = 128,
        double_layer_radial_quadrature_order: int = 128,
        dielectric: float,
        dtype: object,
        device: object,
    ) -> None:
        if isinstance(dielectric, bool) or not isinstance(
            dielectric, (int, float, np.number)
        ):
            raise TypeError("dielectric must be a real scalar.")
        epsilon = float(dielectric)
        if not np.isfinite(epsilon) or epsilon <= 1.0:
            raise ValueError("finite-dielectric ddPCM requires dielectric > 1.")
        double_order = _bounded_order(
            double_layer_radial_quadrature_order,
            name="double_layer_radial_quadrature_order",
        )
        object.__setattr__(self, "_double_layer_radial_order", double_order)
        super().__init__(
            atomic_numbers=atomic_numbers,
            radii_angstrom=radii_angstrom,
            transition_width_angstrom2=transition_width_angstrom2,
            surface_lmax=surface_lmax,
            partition_lmax=partition_lmax,
            partition_radial_quadrature_order=partition_radial_quadrature_order,
            source_radial_quadrature_order=source_radial_quadrature_order,
            dielectric=epsilon,
            dtype=dtype,
            device=device,
        )
        configuration = _sha(self._configuration_payload())
        provenance = _sha(
            {
                "provider_id": self.provider_id,
                "configuration_sha256": configuration,
                "implementation_sha256": self._implementation_fingerprint(),
                "ddx_equation_reference_commit": DDX_EQUATION_REFERENCE_COMMIT,
                "scientific_status": "disabled-research-finite-dielectric-ddpcm",
            }
        )
        object.__setattr__(self, "_candidate_configuration_sha256", configuration)
        object.__setattr__(self, "_candidate_provenance_sha256", provenance)

    @property
    def double_layer_radial_quadrature_order(self) -> int:
        return self._double_layer_radial_order

    @property
    def dielectric_jump_factor(self) -> float:
        return (self._dielectric + 1.0) / (self._dielectric - 1.0)

    def _implementation_fingerprint(self) -> tuple[tuple[str, str], ...]:
        """Return the content-addressed implementation owned by this candidate.

        Model-specific subclasses may extend this tuple with their binding
        module.  Keeping that extension virtual prevents a MACE-POLAR research
        identity from silently covering an AIMNet2-specific factory contract.
        """

        return _implementation_sha256()

    def _configuration_payload(self) -> dict[str, object]:
        return {
            "provider_id": self.provider_id,
            "functional_contract_id": self.functional_contract_id,
            "continuum_profile_id": self.continuum_profile_id,
            "scalar_id": self.scalar_id,
            "atomic_numbers": self._expected_atomic_numbers,
            "radii_angstrom": self._radii_angstrom,
            "transition_width_angstrom2": self._transition_width_angstrom2,
            "surface_lmax": self._surface_lmax,
            "partition_lmax": self._partition_lmax,
            "partition_radial_quadrature_order": self._partition_radial_order,
            "source_radial_quadrature_order": self._source_radial_order,
            "double_layer_radial_quadrature_order": self._double_layer_radial_order,
            "dielectric": self._dielectric,
            "dielectric_jump_factor": self.dielectric_jump_factor,
            "source_space_sha256": ATOMIC_L1_SOURCE_SPACE.metadata_hash(),
            "field_space_sha256": ATOMIC_L1_FIELD_DUAL_SPACE.metadata_hash(),
            "pairing_sha256": ATOMIC_L1_PAIRING.metadata_hash(),
            "runtime_dtype": self._runtime_dtype,
            "runtime_device": self._runtime_device,
            "assembly": "A_eps G=A_inf F; L X=G; F=-B c; G_pcm=1/2 c.T C X",
            "double_layer": (
                "outward-source-normal Laplace principal value; ddX exterior "
                "multipole continuation; centered pair characteristic applied "
                "before coefficient projection"
            ),
            "partition": "polynomial-Shapley-coefficient-partition-v1",
            "ddpcm_characteristic": (
                "centered-c-infinity-pair-product-coefficient-field-v1"
            ),
            "angular_contractions": "finite-band-exact-and-invariant-pair-axis",
            "ddx_equation_reference_commit": DDX_EQUATION_REFERENCE_COMMIT,
            "uniform_cosmo_dielectric_scaling": False,
            "point_monopoles_only": self.point_monopoles_only,
            "capabilities": "none",
            "implementation_sha256": self._implementation_fingerprint(),
        }

    def configuration_sha256(self) -> str:
        current = _sha(self._configuration_payload())
        if current != self._candidate_configuration_sha256:
            raise RuntimeError("smooth harmonic ddPCM configuration drifted.")
        expected_provenance = _sha(
            {
                "provider_id": self.provider_id,
                "configuration_sha256": current,
                "implementation_sha256": self._implementation_fingerprint(),
                "ddx_equation_reference_commit": DDX_EQUATION_REFERENCE_COMMIT,
                "scientific_status": "disabled-research-finite-dielectric-ddpcm",
            }
        )
        if expected_provenance != self._candidate_provenance_sha256:
            raise RuntimeError("smooth harmonic ddPCM provenance drifted.")
        return current

    @staticmethod
    def _operator_condition(operator: Any, *, name: str) -> tuple[float, float]:
        singular_values = __import__("torch").linalg.svdvals(operator).detach()
        relative = float((singular_values[-1] / singular_values[0]).cpu())
        condition = float((singular_values[0] / singular_values[-1]).cpu())
        if (
            not np.isfinite(relative)
            or relative <= _MINIMUM_RELATIVE_SINGULAR_VALUE
            or not np.isfinite(condition)
            or condition > _MAXIMUM_CONDITION_NUMBER
        ):
            raise ValueError(
                f"smooth harmonic ddPCM {name} failed its invertibility gate."
            )
        return relative, condition

    def _assemble_torch(self, positions: Any):
        assembly = _assemble_point_ddpcm(
            positions,
            radii=self._radii_angstrom,
            transition_width=self._transition_width_angstrom2,
            lmax=self._surface_lmax,
            partition_lmax=self._partition_lmax,
            partition_radial_order=self._partition_radial_order,
            source_radial_order=self._source_radial_order,
            double_layer_radial_order=self._double_layer_radial_order,
            dielectric=self._dielectric,
            point_monopoles_only=self.point_monopoles_only,
        )
        self._operator_condition(assembly.schwarz_operator, name="Schwarz operator")
        self._operator_condition(
            assembly.dielectric_operator, name="finite-dielectric operator"
        )
        return assembly

    @staticmethod
    def _solve_primal(assembly: Any, vector: Any) -> tuple[Any, Any, Any]:
        localized_solute_potential = -(assembly.source_operator @ vector)
        intermediate_potential = __import__("torch").linalg.solve(
            assembly.dielectric_operator,
            assembly.conductor_operator @ localized_solute_potential,
        )
        reaction_coefficients = __import__("torch").linalg.solve(
            assembly.schwarz_operator, intermediate_potential
        )
        return (
            localized_solute_potential,
            intermediate_potential,
            reaction_coefficients,
        )

    def _energy_torch(self, positions: Any, source: Any):
        self.configuration_sha256()
        assembly = self._assemble_torch(positions)
        vector = source.reshape(-1)
        _solute, _intermediate, reaction = self._solve_primal(assembly, vector)
        return 0.5 * (vector @ (assembly.receiver @ reaction))

    def debug_geometry_matrices(self, geometry: object) -> dict[str, np.ndarray]:
        positions = self._positions_tensor(
            geometry,
            atom_count=len(self._radii_angstrom),
            requires_grad=False,
        )
        assembly = self._assemble_torch(positions)
        exposed = __import__("torch").stack(
            tuple(item[0] for item in assembly.partition)
        )
        values = {
            key: value
            for key, value in assembly._asdict().items()
            if key != "partition"
        }
        values["exposed_coefficients"] = exposed
        return {
            name: np.asarray(value.detach().cpu(), dtype=float).copy()
            for name, value in values.items()
        }

    def debug_primal_state(
        self, geometry: object, source: object
    ) -> dict[str, np.ndarray | float]:
        values = self.source_space.validate(
            source,
            atom_count=len(self._radii_angstrom),
            name="smooth harmonic ddPCM debug source",
        )
        positions = self._positions_tensor(
            geometry,
            atom_count=len(self._radii_angstrom),
            requires_grad=False,
        )
        source_tensor = self._source_tensor(values, requires_grad=False)
        assembly = self._assemble_torch(positions)
        localized, intermediate, reaction = self._solve_primal(
            assembly, source_tensor.reshape(-1)
        )
        dielectric_rhs = assembly.conductor_operator @ localized
        return {
            "localized_solute_potential": np.asarray(
                localized.detach().cpu(), dtype=float
            ).copy(),
            "intermediate_potential": np.asarray(
                intermediate.detach().cpu(), dtype=float
            ).copy(),
            "reaction_coefficients": np.asarray(
                reaction.detach().cpu(), dtype=float
            ).copy(),
            "dielectric_residual_norm": float(
                __import__("torch")
                .linalg.vector_norm(
                    assembly.dielectric_operator @ intermediate - dielectric_rhs
                )
                .detach()
                .cpu()
            ),
            "schwarz_residual_norm": float(
                __import__("torch")
                .linalg.vector_norm(assembly.schwarz_operator @ reaction - intermediate)
                .detach()
                .cpu()
            ),
        }

    def source_covector_response_operator(self, geometry: object) -> np.ndarray:
        """Return the exact symmetric Hessian of the scalar with respect to source.

        The ddPCM solves are linear at fixed geometry, so the full source
        Hessian can be assembled with matrix right-hand sides rather than one
        autodiff solve per basis vector.  Symmetrisation is not an independent
        physical approximation: it is exactly the Hessian of
        ``0.5*c.T*C*X(c)`` for the generally nonsymmetric discrete operators.
        """

        positions = self._positions_tensor(
            geometry,
            atom_count=len(self._radii_angstrom),
            requires_grad=False,
        )
        assembly = self._assemble_torch(positions)
        torch = __import__("torch")
        localized_operator = -assembly.source_operator
        intermediate_operator = torch.linalg.solve(
            assembly.dielectric_operator,
            assembly.conductor_operator @ localized_operator,
        )
        reaction_operator = torch.linalg.solve(
            assembly.schwarz_operator,
            intermediate_operator,
        )
        raw = assembly.receiver @ reaction_operator
        hessian = 0.5 * (raw + raw.mT)
        result = np.asarray(hessian.detach().cpu(), dtype=float).copy()
        expected = len(self._radii_angstrom) * self.source_space.component_count
        if result.shape != (expected, expected) or not np.all(np.isfinite(result)):
            raise RuntimeError("smooth harmonic ddPCM source Hessian is invalid.")
        return result

    def runtime_provenance(self) -> tuple[tuple[str, object], ...]:
        return tuple(
            sorted(
                {
                    "provider_id": self.provider_id,
                    "configuration_sha256": self.configuration_sha256(),
                    "provenance_sha256": self.provenance_sha256,
                    "continuum_profile_id": self.continuum_profile_id,
                    "scalar_id": self.scalar_id,
                    "stationary_equations": "A_eps G=A_inf F; L X=G; F=-B c",
                    "scalar": "1/2 c.T C X",
                    "dielectric": self._dielectric,
                    "dielectric_jump_factor": self.dielectric_jump_factor,
                    "surface_lmax": self._surface_lmax,
                    "partition_lmax": self._partition_lmax,
                    "double_layer_radial_quadrature_order": (
                        self._double_layer_radial_order
                    ),
                    "ddpcm_characteristic": (
                        "centered-c-infinity-pair-product-coefficient-field-v1"
                    ),
                    "ddx_equation_reference_commit": DDX_EQUATION_REFERENCE_COMMIT,
                    "uniform_cosmo_dielectric_scaling": False,
                    "laboratory_fixed_surface_grid": False,
                    "capabilities": "none",
                }.items()
            )
        )


__all__ = [
    "DDX_EQUATION_REFERENCE_COMMIT",
    "SMOOTH_PARTITION_HARMONIC_DDPCM_CONTRACT_ID",
    "SMOOTH_PARTITION_HARMONIC_DDPCM_PROFILE_ID",
    "SMOOTH_PARTITION_HARMONIC_DDPCM_PROVIDER_ID",
    "SMOOTH_PARTITION_HARMONIC_DDPCM_SCALAR_ID",
    "SmoothPartitionHarmonicDDPCMFunctionalCandidate",
]
