"""PyTorch COSMO-RS primitives and kinetic-solvent-effect arithmetic."""

from .cosmospace import (
    OPEN_COSMORS_24A_PARAMETERS,
    COSMOSPACEParameters,
    COSMOSPACEResult,
    build_segment_interaction_energy,
    molecule_residual_log_activity,
    solve_cosmospace,
)
from .kse import (
    ActivationSolvationFreeEnergy,
    RelativeKineticSolventEffect,
    SolvationFreeEnergy,
    compute_relative_kinetic_solvent_effect,
)
from .ionic_es import (
    IONIC_ES_PAPER_DOI,
    IONIC_ES_THESIS_URL,
    PARAMETERIZATION_C_NEUTRAL_IDENTITY,
    POLYATOMIC_ANION_SHORT_RANGE_IDENTITY,
    PUBLISHED_PARAMETERIZATION_C_NEUTRAL_COSMOSPACE,
    PUBLISHED_POLYATOMIC_ANION_SHORT_RANGE,
    PolyatomicAnionShortRangeParameters,
    parameterization_c_neutral_hbond_weights,
    parameterization_c_neutral_provenance,
    polyatomic_anion_neutral_solvent_cross_energy,
    replace_polyatomic_anion_cross_contacts,
)
from .segment_cosmo import (
    TORCH_SEGMENT_COSMO_MODEL_ID,
    TORCH_SEGMENT_COSMO_PROVIDER_ID,
    TorchSegmentCOSMO,
    TorchSegmentCOSMOConfig,
    TorchSegmentCOSMOFunctional,
    TorchSegmentCOSMOState,
)
from .surface import (
    COSMOSurface,
    SigmaProfile,
    build_sigma_profile,
    discretize_open24a_profile,
    parse_orca_cosmo,
    read_sigma_profile,
    sigma_average,
    sigma_profile_payload,
    write_sigma_profile,
)
from .thermodynamics import (
    OPEN_COSMORS_24A_SOLVATION_PARAMETERS,
    PARAMETERIZATION_C_NEUTRAL_COMBINATORIAL_PARAMETERS,
    InfiniteDilutionActivity,
    OpenCOSMORS24aSolvationParameters,
    OpenCOSMORS24aSolvationResult,
    estimate_open24a_liquid_molar_volume_cm3_mol,
    infinite_dilution_activity,
    open24a_solvation_free_energy,
    staverman_guggenheim_infinite_dilution,
)

__all__ = [
    "OPEN_COSMORS_24A_PARAMETERS",
    "ActivationSolvationFreeEnergy",
    "COSMOSPACEParameters",
    "COSMOSPACEResult",
    "RelativeKineticSolventEffect",
    "SolvationFreeEnergy",
    "COSMOSurface",
    "InfiniteDilutionActivity",
    "IONIC_ES_PAPER_DOI",
    "IONIC_ES_THESIS_URL",
    "OPEN_COSMORS_24A_SOLVATION_PARAMETERS",
    "PARAMETERIZATION_C_NEUTRAL_COMBINATORIAL_PARAMETERS",
    "PARAMETERIZATION_C_NEUTRAL_IDENTITY",
    "OpenCOSMORS24aSolvationParameters",
    "OpenCOSMORS24aSolvationResult",
    "POLYATOMIC_ANION_SHORT_RANGE_IDENTITY",
    "PUBLISHED_PARAMETERIZATION_C_NEUTRAL_COSMOSPACE",
    "PUBLISHED_POLYATOMIC_ANION_SHORT_RANGE",
    "PolyatomicAnionShortRangeParameters",
    "SigmaProfile",
    "TORCH_SEGMENT_COSMO_MODEL_ID",
    "TORCH_SEGMENT_COSMO_PROVIDER_ID",
    "TorchSegmentCOSMO",
    "TorchSegmentCOSMOConfig",
    "TorchSegmentCOSMOFunctional",
    "TorchSegmentCOSMOState",
    "build_segment_interaction_energy",
    "build_sigma_profile",
    "compute_relative_kinetic_solvent_effect",
    "discretize_open24a_profile",
    "estimate_open24a_liquid_molar_volume_cm3_mol",
    "infinite_dilution_activity",
    "molecule_residual_log_activity",
    "open24a_solvation_free_energy",
    "parameterization_c_neutral_hbond_weights",
    "parameterization_c_neutral_provenance",
    "parse_orca_cosmo",
    "polyatomic_anion_neutral_solvent_cross_energy",
    "read_sigma_profile",
    "replace_polyatomic_anion_cross_contacts",
    "sigma_profile_payload",
    "sigma_average",
    "solve_cosmospace",
    "staverman_guggenheim_infinite_dilution",
    "write_sigma_profile",
]
