#!/usr/bin/env python3
"""Train the preregistered MDP-descriptor block-passive P13 response pilot.

The MACE-MDP point ``q/p`` permanent source is not modified here.  This script
learns only the first-order induced response from QM exterior-MEP and molecular
dipole response observables.  Every predicted response source is generated by
differentiating one quadratic field scalar; no source coefficients, PCM values,
solvation labels, or original MACE-POLAR response are targets.
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import platform
import random
import shutil
import sys
from typing import Any

from ase.units import Bohr, Hartree
import numpy as np
import torch


SOURCE_ROOT = Path(__file__).resolve().parents[2]
if str(SOURCE_ROOT) not in sys.path:
    sys.path.insert(0, str(SOURCE_ROOT))

from maple.solvation.coupling.exact_gto import (  # noqa: E402
    FixedSurfaceGeometry,
    MACEPolarRadialGTOCoupling,
)
from maple.solvation.coupling.gaussian_quadrupole import (  # noqa: E402
    gaussian_traceless_quadrupole_surface_operator,
)
from maple.solvation.models.passive_p13_response import (  # noqa: E402
    p13_induced_source_from_scalar_torch,
    p13_response_mep_torch,
    radial_source_molecular_dipole_torch,
    radial_source_total_charge_torch,
)


SELF_REPO_PATH = (
    "tools/route2_release/train_vqm24_mdp_p13_passive_response_pilot.py"
)
ARTIFACT = "route2-vqm24-mdp-p13-block-passive-response-pilot-v1"
PREREGISTRATION_ARTIFACT = (
    "route2-vqm24-mdp-p13-block-passive-response-pilot-prereg-v1"
)
PARENT_ARTIFACT = "route2-vqm24-observable-training-batch-dense-prereg-v2"
ELEMENTS = (1, 6, 7, 8, 9, 15, 16, 17, 35)
ELEMENT_INDEX = {number: index for index, number in enumerate(ELEMENTS)}
SIGMA_L2_ANGSTROM = 1.5
EDGE_CUTOFF_ANGSTROM = 5.0
NEIGHBOR_SCALE_ANGSTROM = 2.0
EDGE_RADIAL_SCALES_ANGSTROM = (1.0, 2.0, 3.0, 4.0)
ELEMENT_EMBEDDING_DIMENSION = 4
ATOM_HIDDEN_WIDTH = 16
EDGE_HIDDEN_WIDTH = 8
ATOM_OUTPUT_DIMENSION = 10
SEED = 20260827
EPOCHS = 1500
LEARNING_RATE = 1.0e-3
WEIGHT_DECAY = 1.0e-4
MEP_LOSS_WEIGHT = 0.82
DIPOLE_LOSS_WEIGHT = 0.18


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _canonical_sha256(payload: object) -> str:
    return hashlib.sha256(
        json.dumps(
            payload,
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=True,
            allow_nan=False,
        ).encode()
    ).hexdigest()


def _smooth_cutoff(distance: torch.Tensor) -> torch.Tensor:
    """C2 quintic cutoff with zero value/first/second derivative at cutoff."""

    ratio = distance / EDGE_CUTOFF_ANGSTROM
    polynomial = 1.0 - 10.0 * ratio**3 + 15.0 * ratio**4 - 6.0 * ratio**5
    return torch.where(
        ratio < 1.0,
        polynomial,
        torch.zeros_like(distance),
    )


def _edge_geometry(
    positions: torch.Tensor,
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    atom_count = len(positions)
    pairs = torch.triu_indices(
        atom_count,
        atom_count,
        offset=1,
        device=positions.device,
    )
    if pairs.numel() == 0:
        return (
            torch.empty((2, 0), dtype=torch.long, device=positions.device),
            torch.empty((0,), dtype=positions.dtype, device=positions.device),
            torch.empty((0,), dtype=positions.dtype, device=positions.device),
        )
    distance = torch.linalg.vector_norm(
        positions[pairs[1]] - positions[pairs[0]],
        dim=1,
    )
    keep = distance < EDGE_CUTOFF_ANGSTROM
    pairs = pairs[:, keep]
    distance = distance[keep]
    return pairs, distance, _smooth_cutoff(distance)


def _raw_atom_features(
    *,
    charges: np.ndarray,
    dipoles: np.ndarray,
    polarizabilities: np.ndarray,
) -> np.ndarray:
    symmetric = 0.5 * (
        polarizabilities + np.swapaxes(polarizabilities, -1, -2)
    )
    trace = np.trace(symmetric, axis1=1, axis2=2)
    frobenius = np.linalg.norm(symmetric, axis=(1, 2))
    dipole_norm = np.linalg.norm(dipoles, axis=1)
    alpha_along_dipole = np.einsum(
        "ni,nij,nj->n",
        dipoles,
        symmetric,
        dipoles,
        optimize=True,
    ) / np.maximum(dipole_norm * dipole_norm, 1.0e-12)
    return np.column_stack(
        (charges, dipole_norm, trace, frobenius, alpha_along_dipole)
    )


def _record_data(
    record: dict[str, Any],
    *,
    mdp_root: Path,
    feature_mean: np.ndarray,
    feature_scale: np.ndarray,
    device: torch.device,
) -> dict[str, Any]:
    record_id = record["record_id"]
    surface_path = Path(record["inputs"]["surface"]["path"])
    modes_path = Path(record["inputs"]["modes"]["path"])
    observable_path = Path(record["outputs"]["observable_npz"])
    with np.load(surface_path, allow_pickle=False) as surface:
        points = np.asarray(surface["surface_points_bohr"], dtype=np.float64)
        positions = np.asarray(surface["atom_positions_angstrom"], dtype=np.float64)
        weights = np.asarray(surface["quadrature_weights"], dtype=np.float64)
        partitions = np.asarray(surface["partition_indices"], dtype=np.int64)
        numbers = np.asarray(surface["atomic_numbers"], dtype=np.int64)
    with np.load(modes_path, allow_pickle=False) as modes:
        source_indices = np.asarray(
            modes["source_surface_indices"], dtype=np.int64
        )
    with np.load(observable_path, allow_pickle=False) as observable:
        target_mep = np.asarray(
            observable["induced_surface_mep_hartree_per_e_per_source_e"],
            dtype=np.float64,
        )
        target_dipole = np.asarray(
            observable["induced_dipole_e_bohr_per_source_e"],
            dtype=np.float64,
        ) * Bohr
    with np.load(mdp_root / record_id / "features.npz", allow_pickle=False) as mdp:
        charges = np.asarray(mdp["charges_e"], dtype=np.float64)
        dipoles = np.asarray(mdp["atomic_dipoles_eangstrom"], dtype=np.float64)
        alpha = np.asarray(
            mdp["atomic_polarizabilities_eangstrom2_per_volt"],
            dtype=np.float64,
        )
    expected_numbers = np.asarray(
        record["selection_record"]["atomic_numbers"], dtype=np.int64
    )
    if not np.array_equal(numbers, expected_numbers):
        raise RuntimeError("QM observable and MDP atom identities differ.")
    if source_indices.shape != (4,) or np.any(partitions[source_indices] != 0):
        raise RuntimeError("Four response source points must remain in fit partition.")
    geometry = FixedSurfaceGeometry(positions, points)
    radial_operator = MACEPolarRadialGTOCoupling().surface_operator(geometry) / Hartree
    l2_operator = gaussian_traceless_quadrupole_surface_operator(
        points_bohr=points,
        centers_angstrom=positions,
        sigma_angstrom=SIGMA_L2_ANGSTROM,
    )
    raw_features = _raw_atom_features(
        charges=charges,
        dipoles=dipoles,
        polarizabilities=alpha,
    )
    normalized_features = (raw_features - feature_mean) / feature_scale
    fit = partitions == 0
    audit = partitions == 1
    normalized_weights = {
        "fit": weights[fit] / np.sum(weights[fit]),
        "audit": weights[audit] / np.sum(weights[audit]),
    }
    positions_t = torch.as_tensor(positions, dtype=torch.float64, device=device)
    edge_index, edge_distance, edge_cutoff = _edge_geometry(positions_t)
    radial_operator_t = torch.as_tensor(
        radial_operator, dtype=torch.float64, device=device
    )
    l2_operator_t = torch.as_tensor(l2_operator, dtype=torch.float64, device=device)
    return {
        "record_id": record_id,
        "element_indices": torch.as_tensor(
            [ELEMENT_INDEX[int(number)] for number in numbers],
            dtype=torch.long,
            device=device,
        ),
        "positions": positions_t,
        "atom_features": torch.as_tensor(
            normalized_features, dtype=torch.float64, device=device
        ),
        "polarizabilities": torch.as_tensor(
            alpha, dtype=torch.float64, device=device
        ),
        "edge_index": edge_index,
        "edge_distance": edge_distance,
        "edge_cutoff": edge_cutoff,
        "radial_operator": radial_operator_t,
        "l2_operator": l2_operator_t,
        "radial_fields": radial_operator_t[source_indices].reshape(
            4, len(positions), 8
        ),
        "l2_fields": l2_operator_t[source_indices].reshape(4, len(positions), 5),
        "target_mep": torch.as_tensor(
            target_mep, dtype=torch.float64, device=device
        ),
        "target_dipole": torch.as_tensor(
            target_dipole, dtype=torch.float64, device=device
        ),
        "source_indices": torch.as_tensor(
            source_indices, dtype=torch.long, device=device
        ),
        "fit_mask": torch.as_tensor(fit, dtype=torch.bool, device=device),
        "audit_mask": torch.as_tensor(audit, dtype=torch.bool, device=device),
        "fit_weights": torch.as_tensor(
            normalized_weights["fit"], dtype=torch.float64, device=device
        ),
        "audit_weights": torch.as_tensor(
            normalized_weights["audit"], dtype=torch.float64, device=device
        ),
    }


class MDPBlockPassiveP13Response(torch.nn.Module):
    """Small MDP-descriptor factor head; it never predicts a source directly."""

    def __init__(self, *, include_edges: bool) -> None:
        super().__init__()
        self.include_edges = bool(include_edges)
        self.element_embedding = torch.nn.Embedding(
            len(ELEMENTS),
            ELEMENT_EMBEDDING_DIMENSION,
            dtype=torch.float64,
        )
        atom_input = 2 * ELEMENT_EMBEDDING_DIMENSION + 5
        self.atom_head = torch.nn.Sequential(
            torch.nn.Linear(atom_input, ATOM_HIDDEN_WIDTH, dtype=torch.float64),
            torch.nn.SiLU(),
            torch.nn.Linear(
                ATOM_HIDDEN_WIDTH,
                ATOM_OUTPUT_DIMENSION,
                dtype=torch.float64,
            ),
        )
        if self.include_edges:
            edge_input = 2 * ELEMENT_EMBEDDING_DIMENSION + 10 + len(
                EDGE_RADIAL_SCALES_ANGSTROM
            )
            self.edge_head = torch.nn.Sequential(
                torch.nn.Linear(edge_input, EDGE_HIDDEN_WIDTH, dtype=torch.float64),
                torch.nn.SiLU(),
                torch.nn.Linear(EDGE_HIDDEN_WIDTH, 2, dtype=torch.float64),
            )
        else:
            self.edge_head = None
        self.scalar_radial_reshape = torch.nn.Parameter(
            torch.zeros((), dtype=torch.float64)
        )
        self.vector_radial_reshape = torch.nn.Parameter(
            torch.zeros((), dtype=torch.float64)
        )
        torch.nn.init.normal_(self.element_embedding.weight, std=0.05)
        torch.nn.init.normal_(self.atom_head[-1].weight, std=0.02)
        torch.nn.init.zeros_(self.atom_head[-1].bias)
        with torch.no_grad():
            self.atom_head[-1].bias[0] = 0.35
            self.atom_head[-1].bias[1] = 0.35
            self.atom_head[-1].bias[7] = 0.35
            self.atom_head[-1].bias[9] = 1.0
        if self.edge_head is not None:
            torch.nn.init.normal_(self.edge_head[-1].weight, std=0.02)
            torch.nn.init.constant_(self.edge_head[-1].bias, 0.05)

    def _atom_coefficients(self, data: dict[str, Any]):
        element = data["element_indices"]
        positions = data["positions"]
        embedding = self.element_embedding(element)
        neighbor = torch.zeros_like(embedding)
        atom_count = len(element)
        for atom_i in range(atom_count):
            for atom_j in range(atom_count):
                if atom_i == atom_j:
                    continue
                distance = torch.linalg.vector_norm(
                    positions[atom_j] - positions[atom_i]
                )
                cutoff = _smooth_cutoff(distance)
                weight = cutoff * torch.exp(-distance / NEIGHBOR_SCALE_ANGSTROM)
                neighbor = neighbor.index_add(
                    0,
                    torch.tensor([atom_i], device=positions.device),
                    (weight * embedding[atom_j])[None],
                )
        values = self.atom_head(
            torch.cat((embedding, neighbor, data["atom_features"]), dim=1)
        )
        return embedding, values

    def _edge_coefficients(
        self,
        *,
        data: dict[str, Any],
        embedding: torch.Tensor,
    ) -> torch.Tensor:
        edge_index = data["edge_index"]
        edge_count = int(edge_index.shape[1])
        if not self.include_edges or edge_count == 0:
            return torch.empty(
                (0, 2), dtype=embedding.dtype, device=embedding.device
            )
        atom_i = edge_index[0]
        atom_j = edge_index[1]
        feature_i = data["atom_features"][atom_i]
        feature_j = data["atom_features"][atom_j]
        radial = torch.stack(
            [
                torch.exp(-data["edge_distance"] / scale)
                for scale in EDGE_RADIAL_SCALES_ANGSTROM
            ],
            dim=1,
        )
        symmetric = torch.cat(
            (
                embedding[atom_i] + embedding[atom_j],
                embedding[atom_i] * embedding[atom_j],
                feature_i + feature_j,
                (feature_i - feature_j).square(),
                radial,
            ),
            dim=1,
        )
        if self.edge_head is None:  # pragma: no cover - guarded above
            raise RuntimeError("edge head is unavailable.")
        return self.edge_head(symmetric)

    def forward(self, data: dict[str, Any], *, create_graph: bool):
        embedding, values = self._atom_coefficients(data)
        radial_gain = values[:, 0]
        vector_coefficients = values[:, 1:9].reshape(-1, 2, 2, 2)
        l2_gain = values[:, 9]
        edge_coefficients = self._edge_coefficients(
            data=data,
            embedding=embedding,
        )
        edge_index = (
            data["edge_index"]
            if self.include_edges
            else torch.empty((2, 0), dtype=torch.long, device=embedding.device)
        )
        edge_cutoff = (
            data["edge_cutoff"]
            if self.include_edges
            else torch.empty((0,), dtype=embedding.dtype, device=embedding.device)
        )
        radial_fields = data["radial_fields"].detach().clone().requires_grad_(True)
        l2_fields = data["l2_fields"].detach().clone().requires_grad_(True)
        energies, radial_source, l2_source = p13_induced_source_from_scalar_torch(
            radial_fields=radial_fields,
            l2_fields=l2_fields,
            l2_gain=l2_gain,
            create_graph=create_graph,
            positions_angstrom=data["positions"],
            edge_index=edge_index,
            atomic_polarizability=data["polarizabilities"],
            radial_gain=radial_gain,
            vector_coefficients=vector_coefficients,
            edge_coefficients=edge_coefficients,
            edge_cutoff=edge_cutoff,
            scalar_radial_reshape=self.scalar_radial_reshape,
            vector_radial_reshape=self.vector_radial_reshape,
        )
        mep = p13_response_mep_torch(
            radial_source=radial_source,
            l2_source=l2_source,
            radial_operator=data["radial_operator"],
            l2_operator=data["l2_operator"],
        )
        dipole = radial_source_molecular_dipole_torch(
            radial_source=radial_source,
            positions_angstrom=data["positions"],
        )
        return {
            "energies": energies,
            "radial_source": radial_source,
            "l2_source": l2_source,
            "mep": mep,
            "dipole": dipole,
        }


def _training_scales(records: list[dict[str, Any]]) -> tuple[float, float]:
    mep = []
    dipole = []
    for record in records:
        fit = record["fit_mask"]
        mep.append(
            float(
                torch.sqrt(
                    torch.mean(
                        torch.sum(
                            record["fit_weights"]
                            * record["target_mep"][:, fit].square(),
                            dim=1,
                        )
                    )
                ).cpu()
            )
        )
        dipole.append(
            float(
                torch.sqrt(
                    torch.mean(torch.sum(record["target_dipole"].square(), dim=1))
                ).cpu()
            )
        )
    result = float(np.median(mep)), float(np.median(dipole))
    if result[0] <= 0.0 or result[1] <= 0.0:
        raise RuntimeError("Response training scales must be positive.")
    return result


def _fit_candidate(
    *,
    candidate_id: str,
    records: list[dict[str, Any]],
    device: torch.device,
    output_directory: Path,
) -> tuple[MDPBlockPassiveP13Response, list[dict[str, float]], dict[str, float]]:
    include_edges = candidate_id == "A3"
    if candidate_id not in {"A2", "A3"}:
        raise ValueError("candidate_id must be A2 or A3.")
    torch.manual_seed(SEED + (1 if include_edges else 0))
    if device.type == "cuda":
        torch.cuda.manual_seed_all(SEED + (1 if include_edges else 0))
    model = MDPBlockPassiveP13Response(include_edges=include_edges).to(device=device)
    parameter_count = sum(parameter.numel() for parameter in model.parameters())
    if parameter_count > 2500:
        raise RuntimeError("MDP-only response head exceeds the frozen parameter cap.")
    mep_scale, dipole_scale = _training_scales(records)
    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=LEARNING_RATE,
        weight_decay=WEIGHT_DECAY,
    )
    history: list[dict[str, float]] = []
    for epoch in range(EPOCHS):
        optimizer.zero_grad(set_to_none=True)
        total_mep = 0.0
        total_dipole = 0.0
        for record in records:
            prediction = model(record, create_graph=True)
            fit = record["fit_mask"]
            mep_loss = torch.mean(
                torch.sum(
                    record["fit_weights"]
                    * (prediction["mep"][:, fit] - record["target_mep"][:, fit]).square(),
                    dim=1,
                )
            ) / (mep_scale * mep_scale)
            dipole_loss = torch.mean(
                torch.sum(
                    (prediction["dipole"] - record["target_dipole"]).square(),
                    dim=1,
                )
            ) / (dipole_scale * dipole_scale)
            loss = (
                MEP_LOSS_WEIGHT * mep_loss
                + DIPOLE_LOSS_WEIGHT * dipole_loss
            ) / len(records)
            loss.backward()
            total_mep += float(mep_loss.detach().cpu()) / len(records)
            total_dipole += float(dipole_loss.detach().cpu()) / len(records)
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=20.0)
        optimizer.step()
        if epoch % 100 == 0 or epoch == EPOCHS - 1:
            history.append(
                {
                    "epoch": float(epoch),
                    "loss": MEP_LOSS_WEIGHT * total_mep
                    + DIPOLE_LOSS_WEIGHT * total_dipole,
                    "mep_loss": total_mep,
                    "dipole_loss": total_dipole,
                }
            )
    candidate_directory = output_directory / candidate_id
    candidate_directory.mkdir(parents=True, exist_ok=False)
    checkpoint = candidate_directory / "head.pt"
    torch.save(
        {
            "candidate_id": candidate_id,
            "state_dict": {
                key: value.detach().cpu() for key, value in model.state_dict().items()
            },
            "elements": ELEMENTS,
            "atom_feature_mean": records[0]["feature_mean"],
            "atom_feature_scale": records[0]["feature_scale"],
            "sigma_l2_angstrom": SIGMA_L2_ANGSTROM,
            "edge_cutoff_angstrom": EDGE_CUTOFF_ANGSTROM,
            "mep_scale": mep_scale,
            "dipole_scale": dipole_scale,
        },
        checkpoint,
    )
    return model, history, {
        "parameter_count": float(parameter_count),
        "mep_scale": mep_scale,
        "dipole_scale": dipole_scale,
        "checkpoint_sha256": _sha256(checkpoint),
    }


def _candidate_metrics(
    *,
    model: MDPBlockPassiveP13Response,
    records: list[dict[str, Any]],
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    metrics: list[dict[str, Any]] = []
    model.eval()
    for record in records:
        with torch.enable_grad():
            prediction = model(record, create_graph=False)
        mep = prediction["mep"].detach()
        dipole = prediction["dipole"].detach()
        radial_source = prediction["radial_source"].detach()
        l2_source = prediction["l2_source"].detach()
        item: dict[str, Any] = {"record_id": record["record_id"]}
        for name in ("fit", "audit"):
            mask = record[f"{name}_mask"]
            weights = record[f"{name}_weights"]
            error = mep[:, mask] - record["target_mep"][:, mask]
            reference = record["target_mep"][:, mask]
            item[f"{name}_mep_relative"] = float(
                torch.sqrt(torch.sum(weights * error.square()))
                / torch.sqrt(torch.sum(weights * reference.square()))
            )
        audit_error = mep[:, record["audit_mask"]] - record["target_mep"][:, record["audit_mask"]]
        item["audit_mep_max_absolute_hartree_per_e_per_source_e"] = float(
            torch.max(torch.abs(audit_error))
        )
        item["dipole_response_relative"] = float(
            torch.linalg.vector_norm(dipole - record["target_dipole"])
            / torch.linalg.vector_norm(record["target_dipole"])
        )
        source_indices = record["source_indices"]
        predicted_source_response = mep[:, source_indices]
        reference_source_response = record["target_mep"][:, source_indices]
        item["source_point_response_relative"] = float(
            torch.linalg.vector_norm(
                predicted_source_response - reference_source_response
            )
            / torch.linalg.vector_norm(reference_source_response)
        )
        item["source_point_reciprocity_relative"] = float(
            torch.linalg.vector_norm(
                predicted_source_response - predicted_source_response.T
            )
            / torch.linalg.vector_norm(predicted_source_response)
        )
        item["source_point_maximum_symmetric_eigenvalue_hartree_per_e2"] = float(
            torch.linalg.eigvalsh(
                0.5 * (predicted_source_response + predicted_source_response.T)
            ).max()
        )
        item["maximum_induced_charge_residual_e"] = float(
            torch.max(torch.abs(radial_source_total_charge_torch(radial_source)))
        )
        item["l2_source_fraction"] = float(
            torch.linalg.vector_norm(l2_source)
            / (
                torch.linalg.vector_norm(radial_source)
                + torch.linalg.vector_norm(l2_source)
                + torch.finfo(torch.float64).tiny
            )
        )
        metrics.append(item)
    fit_values = np.asarray([item["fit_mep_relative"] for item in metrics])
    audit_values = np.asarray([item["audit_mep_relative"] for item in metrics])
    aggregate: dict[str, Any] = {
        "mean_fit_mep_relative": float(np.mean(fit_values)),
        "mean_audit_mep_relative": float(np.mean(audit_values)),
        "maximum_audit_mep_relative": float(np.max(audit_values)),
        "maximum_audit_mep_max_absolute_hartree_per_e_per_source_e": max(
            item["audit_mep_max_absolute_hartree_per_e_per_source_e"]
            for item in metrics
        ),
        "mean_dipole_response_relative": float(
            np.mean([item["dipole_response_relative"] for item in metrics])
        ),
        "maximum_dipole_response_relative": max(
            item["dipole_response_relative"] for item in metrics
        ),
        "mean_source_point_response_relative": float(
            np.mean([item["source_point_response_relative"] for item in metrics])
        ),
        "maximum_source_point_response_relative": max(
            item["source_point_response_relative"] for item in metrics
        ),
        "maximum_source_point_reciprocity_relative": max(
            item["source_point_reciprocity_relative"] for item in metrics
        ),
        "maximum_source_point_symmetric_eigenvalue_hartree_per_e2": max(
            item["source_point_maximum_symmetric_eigenvalue_hartree_per_e2"]
            for item in metrics
        ),
        "maximum_induced_charge_residual_e": max(
            item["maximum_induced_charge_residual_e"] for item in metrics
        ),
        "maximum_individual_audit_to_fit_ratio": float(
            np.max(audit_values / np.maximum(fit_values, np.finfo(float).tiny))
        ),
        "mean_audit_to_fit_ratio": float(
            np.mean(audit_values) / max(float(np.mean(fit_values)), np.finfo(float).tiny)
        ),
        "mean_l2_source_fraction": float(
            np.mean([item["l2_source_fraction"] for item in metrics])
        ),
    }
    aggregate["selection_score"] = (
        0.80 * aggregate["mean_audit_mep_relative"]
        + 0.20 * aggregate["mean_dipole_response_relative"]
    )
    return metrics, aggregate


def _gate_candidate(
    aggregate: dict[str, Any], gates: dict[str, Any]
) -> dict[str, bool]:
    return {
        "mean_audit_mep": aggregate["mean_audit_mep_relative"]
        <= gates["mean_audit_mep_relative_maximum"],
        "worst_audit_mep": aggregate["maximum_audit_mep_relative"]
        <= gates["maximum_audit_mep_relative"],
        "audit_mep_absolute": aggregate[
            "maximum_audit_mep_max_absolute_hartree_per_e_per_source_e"
        ]
        <= gates["maximum_audit_mep_absolute_hartree_per_e_per_source_e"],
        "mean_dipole_response": aggregate["mean_dipole_response_relative"]
        <= gates["mean_dipole_response_relative_maximum"],
        "worst_dipole_response": aggregate["maximum_dipole_response_relative"]
        <= gates["maximum_dipole_response_relative"],
        "mean_source_point_response": aggregate[
            "mean_source_point_response_relative"
        ]
        <= gates["mean_source_point_response_relative_maximum"],
        "worst_source_point_response": aggregate[
            "maximum_source_point_response_relative"
        ]
        <= gates["maximum_source_point_response_relative"],
        "reciprocity": aggregate["maximum_source_point_reciprocity_relative"]
        <= gates["maximum_source_point_reciprocity_relative"],
        "passivity": aggregate[
            "maximum_source_point_symmetric_eigenvalue_hartree_per_e2"
        ]
        <= gates["maximum_source_point_symmetric_eigenvalue_hartree_per_e2"],
        "charge": aggregate["maximum_induced_charge_residual_e"]
        <= gates["maximum_induced_charge_residual_e"],
        "mean_fit_audit_generalization": aggregate["mean_audit_to_fit_ratio"]
        <= gates["mean_audit_to_fit_ratio_maximum"],
        "individual_fit_audit_generalization": aggregate[
            "maximum_individual_audit_to_fit_ratio"
        ]
        <= gates["maximum_individual_audit_to_fit_ratio"],
    }


def run(args: argparse.Namespace) -> dict[str, Any]:
    preregistration_path = args.preregistration.expanduser().resolve(strict=True)
    mdp_root = args.mdp_features.expanduser().resolve(strict=True)
    output_directory = args.output_directory.expanduser().resolve()
    if output_directory.exists():
        raise FileExistsError(output_directory)
    preregistration = json.loads(preregistration_path.read_text())
    if (
        preregistration.get("artifact") != PREREGISTRATION_ARTIFACT
        or preregistration.get("status") != "locked-before-training"
    ):
        raise ValueError("P13 response preregistration is invalid.")
    if _sha256(SOURCE_ROOT / SELF_REPO_PATH) != preregistration["source"][
        "training_runner_sha256"
    ]:
        raise RuntimeError("Training runner changed after preregistration.")
    for name in ("factor", "response", "radial_coupling", "l2_coupling"):
        entry = preregistration["source"][name]
        if _sha256(SOURCE_ROOT / entry["path"]) != entry["sha256"]:
            raise RuntimeError(f"Frozen response source changed: {name}.")
    if _sha256(mdp_root / "manifest.json") != preregistration["inputs"][
        "mdp_feature_manifest_sha256"
    ]:
        raise RuntimeError("Frozen MDP feature manifest changed.")
    parent_path = SOURCE_ROOT / preregistration["parent"]["path"]
    if _sha256(parent_path) != preregistration["parent"]["file_sha256"]:
        raise RuntimeError("Observable parent changed after response freeze.")
    parent = json.loads(parent_path.read_text())
    if parent.get("artifact") != PARENT_ARTIFACT:
        raise ValueError("Observable parent has the wrong identity.")
    if [record["record_id"] for record in parent["records"]] != preregistration[
        "train_record_ids"
    ]:
        raise RuntimeError("Response train-record order changed.")
    device = torch.device(args.device)
    if device.type == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("Requested CUDA response training is unavailable.")
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)
    if device.type == "cuda":
        torch.cuda.manual_seed_all(SEED)
    raw_features = []
    for record in parent["records"]:
        record_id = record["record_id"]
        with np.load(
            mdp_root / record_id / "features.npz", allow_pickle=False
        ) as mdp:
            raw_features.append(
                _raw_atom_features(
                    charges=np.asarray(mdp["charges_e"], dtype=np.float64),
                    dipoles=np.asarray(
                        mdp["atomic_dipoles_eangstrom"], dtype=np.float64
                    ),
                    polarizabilities=np.asarray(
                        mdp["atomic_polarizabilities_eangstrom2_per_volt"],
                        dtype=np.float64,
                    ),
                )
            )
    joined = np.concatenate(raw_features, axis=0)
    feature_mean = np.mean(joined, axis=0)
    feature_scale = np.std(joined, axis=0)
    feature_scale = np.maximum(feature_scale, 1.0e-8)
    records = [
        _record_data(
            record,
            mdp_root=mdp_root,
            feature_mean=feature_mean,
            feature_scale=feature_scale,
            device=device,
        )
        for record in parent["records"]
    ]
    for record in records:
        record["feature_mean"] = feature_mean.tolist()
        record["feature_scale"] = feature_scale.tolist()
    output_directory.mkdir(parents=True, exist_ok=False)
    candidates: dict[str, Any] = {}
    previous_score = None
    for candidate_id in preregistration["candidate_sequence"]:
        model, history, fit_metadata = _fit_candidate(
            candidate_id=candidate_id,
            records=records,
            device=device,
            output_directory=output_directory,
        )
        metrics, aggregate = _candidate_metrics(model=model, records=records)
        gates = _gate_candidate(aggregate, preregistration["gates"])
        gate_passed = all(gates.values())
        if previous_score is None:
            relative_improvement = None
        else:
            relative_improvement = (previous_score - aggregate["selection_score"]) / previous_score
        candidates[candidate_id] = {
            "architecture": {
                "include_edges": candidate_id == "A3",
                "trainable_parameter_count": int(fit_metadata["parameter_count"]),
                "new_message_passing": False,
                "backbone_parameters_trainable": False,
                "full_p13_induced_response": True,
                "response_source_implemented_separately": False,
            },
            "training": {
                "history": history,
                "mep_scale_hartree_per_e_per_source_e": fit_metadata["mep_scale"],
                "dipole_scale_eangstrom_per_source_e": fit_metadata["dipole_scale"],
                "checkpoint_sha256": fit_metadata["checkpoint_sha256"],
            },
            "metrics": metrics,
            "aggregate": aggregate,
            "gates": gates,
            "gate_passed": gate_passed,
            "relative_score_improvement_over_previous": relative_improvement,
        }
        (output_directory / candidate_id / "result.json").write_text(
            json.dumps(candidates[candidate_id], indent=2, sort_keys=True) + "\n"
        )
        previous_score = aggregate["selection_score"]
        if gate_passed:
            break
    selected = None
    for candidate_id, candidate in candidates.items():
        if candidate["gate_passed"]:
            selected = candidate_id
            break
    payload: dict[str, Any] = {
        "artifact": ARTIFACT,
        "schema_version": 1,
        "status": (
            "pass-development-response-pilot"
            if selected is not None
            else "fail-development-response-pilot"
        ),
        "created_utc": datetime.now(timezone.utc).isoformat(),
        "source": {
            "runner_path": SELF_REPO_PATH,
            "runner_sha256": _sha256(SOURCE_ROOT / SELF_REPO_PATH),
            "preregistration_file_sha256": _sha256(preregistration_path),
            "preregistration_sha256": preregistration["preregistration_sha256"],
            "parent_file_sha256": _sha256(parent_path),
            "mdp_feature_manifest_sha256": _sha256(mdp_root / "manifest.json"),
        },
        "fixed_contract": {
            "permanent_source": "existing MACE-MDP point q/p affine source; not trained",
            "response_scalar": "-1/2 ||C_theta(R) eta_P13||^2",
            "l2_kernel": f"Gaussian STF sigma={SIGMA_L2_ANGSTROM} angstrom",
            "induced_source": "autograd of the sole response scalar",
            "factor": "atom radial-null + two atom vector + local l2; optional symmetric edge row",
            "edge_cutoff": "C2 quintic at 5.0 angstrom",
        },
        "training": {
            "device": str(device),
            "dtype": "float64",
            "seed": SEED,
            "epochs": EPOCHS,
            "learning_rate": LEARNING_RATE,
            "weight_decay": WEIGHT_DECAY,
            "mep_loss_weight": MEP_LOSS_WEIGHT,
            "dipole_loss_weight": DIPOLE_LOSS_WEIGHT,
            "audit_points_used_in_gradient": False,
            "atom_feature_mean": feature_mean.tolist(),
            "atom_feature_scale": feature_scale.tolist(),
        },
        "candidates": candidates,
        "selected_candidate_for_grouped_cv": selected,
        "claim_boundary": {
            "development_train_formulas_only": True,
            "validation_or_blind_formula_opened": False,
            "per_molecule_source_coefficient_label_used": False,
            "original_mace_polar_source_or_response_used": False,
            "experimental_solvation_target_read": False,
            "pcm_or_cavity_used": False,
            "permanent_mdp_source_modified": False,
            "grouped_formula_cv_completed": False,
            "model_selected_or_admitted": False,
            "maple_capability_admitted": False,
        },
        "runtime": {
            "python": platform.python_version(),
            "python_executable": sys.executable,
            "numpy": np.__version__,
            "torch": torch.__version__,
        },
    }
    payload["result_sha256"] = _canonical_sha256(payload)
    shutil.copy2(preregistration_path, output_directory / "preregistration.json")
    result_path = output_directory / "result.json"
    result_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    result_path.chmod(0o444)
    return payload


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--preregistration", type=Path, required=True)
    parser.add_argument("--mdp-features", type=Path, required=True)
    parser.add_argument("--output-directory", type=Path, required=True)
    parser.add_argument("--device", default="cuda")
    args = parser.parse_args()
    print(json.dumps(run(args), indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
